

spring:
  datasource:
    profile: r
    username: root
    url: jdbc:mariadb://localhost:3306/dev?createDatabaseIfNotExist=true
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update


server:
  port: 1111

