

spring:
  datasource:
    profile: production
    username: root
    url: jdbc:mariadb://localhost:3306/store?createDatabaseIfNotExist=true
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update


server:
  port: 8081